spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.199.75.133:3306/picshare_userms?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  application:
    name: picshare-member
  cloud:
    nacos:
      discovery:
        server-addr: 121.199.75.133:8848

mybatis-plus:
  type-aliases-package: com.picshare.member.entity
  mapper-locations: classpath:mapper.member/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8100

